services:
  mysql:
    image: mysql:8.4
    container_name: travelit-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: travelit
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - travelit_mysql_data:/var/lib/mysql

volumes:
  travelit_mysql_data:
