/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedBudgetRouteImport } from './routes/_authenticated/budget'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedExploreRouteImport } from './routes/_authenticated/explore'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as Oauth2SuccessRouteImport } from './routes/oauth2.success'
import { Route as AuthenticatedDestinationsIndexRouteImport } from './routes/_authenticated/destinations.index'
import { Route as AuthenticatedDestinationsDestinationIdRouteImport } from './routes/_authenticated/destinations.$destinationId'
import { Route as AuthenticatedPlacesIndexRouteImport } from './routes/_authenticated/places.index'
import { Route as AuthenticatedPlacesPlaceIdRouteImport } from './routes/_authenticated/places.$placeId'
import { Route as AuthenticatedTripsIndexRouteImport } from './routes/_authenticated/trips.index'
import { Route as AuthenticatedTripsTripIdRouteImport } from './routes/_authenticated/trips.$tripId'
import { Route as AuthenticatedTripsCreateRouteImport } from './routes/_authenticated/trips.create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBudgetRoute = AuthenticatedBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExploreRoute = AuthenticatedExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const Oauth2SuccessRoute = Oauth2SuccessRouteImport.update({
  id: '/oauth2/success',
  path: '/oauth2/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDestinationsIndexRoute =
  AuthenticatedDestinationsIndexRouteImport.update({
    id: '/destinations/',
    path: '/destinations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDestinationsDestinationIdRoute =
  AuthenticatedDestinationsDestinationIdRouteImport.update({
    id: '/destinations/$destinationId',
    path: '/destinations/$destinationId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlacesIndexRoute =
  AuthenticatedPlacesIndexRouteImport.update({
    id: '/places/',
    path: '/places/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlacesPlaceIdRoute =
  AuthenticatedPlacesPlaceIdRouteImport.update({
    id: '/places/$placeId',
    path: '/places/$placeId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTripsIndexRoute = AuthenticatedTripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTripsTripIdRoute =
  AuthenticatedTripsTripIdRouteImport.update({
    id: '/trips/$tripId',
    path: '/trips/$tripId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTripsCreateRoute =
  AuthenticatedTripsCreateRouteImport.update({
    id: '/trips/create',
    path: '/trips/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/budget': typeof AuthenticatedBudgetRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/oauth2/success': typeof Oauth2SuccessRoute
  '/destinations/$destinationId': typeof AuthenticatedDestinationsDestinationIdRoute
  '/places/$placeId': typeof AuthenticatedPlacesPlaceIdRoute
  '/trips/$tripId': typeof AuthenticatedTripsTripIdRoute
  '/trips/create': typeof AuthenticatedTripsCreateRoute
  '/destinations/': typeof AuthenticatedDestinationsIndexRoute
  '/places/': typeof AuthenticatedPlacesIndexRoute
  '/trips/': typeof AuthenticatedTripsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/budget': typeof AuthenticatedBudgetRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/oauth2/success': typeof Oauth2SuccessRoute
  '/destinations/$destinationId': typeof AuthenticatedDestinationsDestinationIdRoute
  '/places/$placeId': typeof AuthenticatedPlacesPlaceIdRoute
  '/trips/$tripId': typeof AuthenticatedTripsTripIdRoute
  '/trips/create': typeof AuthenticatedTripsCreateRoute
  '/destinations': typeof AuthenticatedDestinationsIndexRoute
  '/places': typeof AuthenticatedPlacesIndexRoute
  '/trips': typeof AuthenticatedTripsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/budget': typeof AuthenticatedBudgetRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/explore': typeof AuthenticatedExploreRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/oauth2/success': typeof Oauth2SuccessRoute
  '/_authenticated/destinations/$destinationId': typeof AuthenticatedDestinationsDestinationIdRoute
  '/_authenticated/places/$placeId': typeof AuthenticatedPlacesPlaceIdRoute
  '/_authenticated/trips/$tripId': typeof AuthenticatedTripsTripIdRoute
  '/_authenticated/trips/create': typeof AuthenticatedTripsCreateRoute
  '/_authenticated/destinations/': typeof AuthenticatedDestinationsIndexRoute
  '/_authenticated/places/': typeof AuthenticatedPlacesIndexRoute
  '/_authenticated/trips/': typeof AuthenticatedTripsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/budget'
    | '/dashboard'
    | '/explore'
    | '/profile'
    | '/oauth2/success'
    | '/destinations/$destinationId'
    | '/places/$placeId'
    | '/trips/$tripId'
    | '/trips/create'
    | '/destinations/'
    | '/places/'
    | '/trips/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/budget'
    | '/dashboard'
    | '/explore'
    | '/profile'
    | '/oauth2/success'
    | '/destinations/$destinationId'
    | '/places/$placeId'
    | '/trips/$tripId'
    | '/trips/create'
    | '/destinations'
    | '/places'
    | '/trips'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/budget'
    | '/_authenticated/dashboard'
    | '/_authenticated/explore'
    | '/_authenticated/profile'
    | '/oauth2/success'
    | '/_authenticated/destinations/$destinationId'
    | '/_authenticated/places/$placeId'
    | '/_authenticated/trips/$tripId'
    | '/_authenticated/trips/create'
    | '/_authenticated/destinations/'
    | '/_authenticated/places/'
    | '/_authenticated/trips/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  Oauth2SuccessRoute: typeof Oauth2SuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/budget': {
      id: '/_authenticated/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof AuthenticatedBudgetRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/explore': {
      id: '/_authenticated/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AuthenticatedExploreRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/oauth2/success': {
      id: '/oauth2/success'
      path: '/oauth2/success'
      fullPath: '/oauth2/success'
      preLoaderRoute: typeof Oauth2SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/destinations/': {
      id: '/_authenticated/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof AuthenticatedDestinationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/destinations/$destinationId': {
      id: '/_authenticated/destinations/$destinationId'
      path: '/destinations/$destinationId'
      fullPath: '/destinations/$destinationId'
      preLoaderRoute: typeof AuthenticatedDestinationsDestinationIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/places/': {
      id: '/_authenticated/places/'
      path: '/places'
      fullPath: '/places/'
      preLoaderRoute: typeof AuthenticatedPlacesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/places/$placeId': {
      id: '/_authenticated/places/$placeId'
      path: '/places/$placeId'
      fullPath: '/places/$placeId'
      preLoaderRoute: typeof AuthenticatedPlacesPlaceIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trips/': {
      id: '/_authenticated/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof AuthenticatedTripsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trips/$tripId': {
      id: '/_authenticated/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof AuthenticatedTripsTripIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trips/create': {
      id: '/_authenticated/trips/create'
      path: '/trips/create'
      fullPath: '/trips/create'
      preLoaderRoute: typeof AuthenticatedTripsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBudgetRoute: typeof AuthenticatedBudgetRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExploreRoute: typeof AuthenticatedExploreRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedDestinationsDestinationIdRoute: typeof AuthenticatedDestinationsDestinationIdRoute
  AuthenticatedPlacesPlaceIdRoute: typeof AuthenticatedPlacesPlaceIdRoute
  AuthenticatedTripsTripIdRoute: typeof AuthenticatedTripsTripIdRoute
  AuthenticatedTripsCreateRoute: typeof AuthenticatedTripsCreateRoute
  AuthenticatedDestinationsIndexRoute: typeof AuthenticatedDestinationsIndexRoute
  AuthenticatedPlacesIndexRoute: typeof AuthenticatedPlacesIndexRoute
  AuthenticatedTripsIndexRoute: typeof AuthenticatedTripsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBudgetRoute: AuthenticatedBudgetRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExploreRoute: AuthenticatedExploreRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedDestinationsDestinationIdRoute:
    AuthenticatedDestinationsDestinationIdRoute,
  AuthenticatedPlacesPlaceIdRoute: AuthenticatedPlacesPlaceIdRoute,
  AuthenticatedTripsTripIdRoute: AuthenticatedTripsTripIdRoute,
  AuthenticatedTripsCreateRoute: AuthenticatedTripsCreateRoute,
  AuthenticatedDestinationsIndexRoute: AuthenticatedDestinationsIndexRoute,
  AuthenticatedPlacesIndexRoute: AuthenticatedPlacesIndexRoute,
  AuthenticatedTripsIndexRoute: AuthenticatedTripsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  Oauth2SuccessRoute: Oauth2SuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
